In [1]:
import numpy as np
import pandas as pd

In [4]:
dataset = pd.read_csv("data.csv", encoding='latin1')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [5]:
print(y)

['ENFP' 'ISFP' 'INFJ' ... 'ISTP' 'ISTJ' 'INFJ']


In [6]:
print(X)

[[ 0  0  0 ...  0  0  0]
 [-2 -3 -1 ...  1 -1  3]
 [ 2  0 -1 ... -1  1  1]
 ...
 [ 1  0 -2 ...  2 -1 -1]
 [ 1 -1 -2 ...  0  0  0]
 [ 2  0 -1 ...  2  1 -1]]


In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_new = le.fit_transform(y)

In [8]:
print(y_new)

[ 1 13  8 ... 15 14  8]


In [69]:
print(y[47:60])

['ESTJ' 'ISFP' 'ESFJ' 'ISTJ' 'ESTJ' 'ESTJ' 'ISFJ' 'ESFP' 'ENFP' 'ESFJ'
 'ISTP' 'ENTP' 'INFP']


In [70]:
print(y_new[47:60])

[ 6 13  4 14  6  6 12  5  1  4 15  3  9]


In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y_new, test_size = 0.25, random_state = 0)

In [60]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 40, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=40)

In [61]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[ 6  6]
 [10 10]
 [ 8  8]
 ...
 [ 9  3]
 [ 4  4]
 [ 3  3]]


In [20]:
#7
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[905   2   0   3   1   1   0   0   0   1   1   3   1   3   0   1]
 [  3 949   0   1   1   0   2   0   0   2   2   2   2   1   0   1]
 [  0   0 887   2   2   0   0   3   1   4   0   0   1   0   1   0]
 [  0   1   0 900   1   2   3   2   2   3   0   3   1   2   1   1]
 [  1   0   0   0 871   1   0   1   7   3   1   1   0   0   0   1]
 [  0   0   3   0   1 917   1   0   3   1   2   1   3   3   1   0]
 [  1   1   3   0   2   2 936   1   1   2   0   2   0   1   0   1]
 [  0   1   3   1   2   1   1 929   0   2   1   1   1   0   1   0]
 [  0   1   3   3   2   4   2   2 874   2   4   8   2   0   0   1]
 [  1   0   9   1   1   0   2   0   0 888   0   0   2   1   0   2]
 [  2   0   1   1   2   3   0   1   0   3 900   1   2   2   1   0]
 [  2   3   3   1   4   1   0   1   2   0   1 941   1   2   1   1]
 [  3   0   0   0   0   3   2   4   1   0   1   2 935   1   0   4]
 [  0   1   0   0   3   0   1   1   1   0   5   2   1 967   0   1]
 [  0   0   1   0   1   0   0   1   2   2   1   2   2   1 966 

0.9795333333333334

In [23]:
#5
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[906   2   1   2   1   1   0   0   0   1   2   3   0   2   0   1]
 [  3 949   0   1   1   0   2   0   0   2   0   3   2   2   0   1]
 [  0   0 886   2   2   0   0   3   1   5   0   0   1   0   1   0]
 [  0   1   0 899   1   2   4   2   2   3   0   3   1   2   1   1]
 [  0   2   0   1 870   1   0   1   4   2   2   2   0   1   0   1]
 [  0   0   3   0   2 916   1   0   2   1   2   1   3   3   2   0]
 [  1   1   2   0   2   2 938   1   1   2   0   2   0   1   0   0]
 [  0   1   3   2   3   1   1 927   1   2   0   1   1   0   1   0]
 [  0   1   3   4   2   6   3   3 870   2   4   7   2   0   0   1]
 [  2   0  11   1   1   0   2   0   0 885   0   0   1   2   0   2]
 [  1   0   2   2   3   3   0   2   1   3 895   1   3   2   1   0]
 [  3   3   5   1   4   1   0   1   3   0   0 939   1   1   1   1]
 [  4   0   0   0   0   3   3   3   2   0   2   2 929   2   0   6]
 [  0   1   0   0   1   2   2   1   2   0   5   4   1 962   0   2]
 [  0   0   3   0   2   0   0   1   2   3   1   2   2   0 962 

0.9772666666666666

In [29]:
#10
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[905   2   0   2   2   0   0   0   0   1   1   3   1   3   0   2]
 [  3 950   0   1   1   0   2   0   0   2   2   1   2   1   0   1]
 [  0   0 887   2   2   0   0   3   1   4   0   0   1   0   1   0]
 [  0   1   0 902   1   2   2   2   2   3   0   2   1   2   1   1]
 [  0   0   0   0 871   1   1   1   6   3   1   2   0   0   0   1]
 [  0   1   4   0   1 916   1   0   1   1   2   1   3   3   1   1]
 [  1   1   2   0   3   2 939   1   1   1   0   1   0   1   0   0]
 [  0   1   3   1   2   2   0 929   0   2   1   1   1   0   1   0]
 [  0   1   3   3   2   5   1   2 875   2   4   7   2   0   0   1]
 [  1   0   9   1   0   0   1   0   0 890   0   0   2   1   0   2]
 [  1   0   1   2   2   2   0   1   0   3 900   1   2   2   2   0]
 [  2   4   3   1   4   1   0   1   1   0   0 943   1   1   1   1]
 [  3   0   0   0   0   2   3   3   1   0   1   2 937   1   0   3]
 [  0   2   0   0   2   1   1   0   1   0   4   2   0 967   1   2]
 [  0   0   1   0   1   0   0   1   2   1   1   1   2   1 968 

0.9802

In [32]:
#13
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[905   2   1   2   1   0   0   0   0   1   2   3   1   3   0   1]
 [  3 948   0   1   1   0   2   0   0   2   2   3   2   1   0   1]
 [  0   0 887   2   2   0   0   3   1   4   0   0   1   0   1   0]
 [  0   1   0 901   1   2   3   2   2   3   0   2   1   2   1   1]
 [  0   0   0   0 873   1   0   1   5   3   1   2   0   0   0   1]
 [  0   1   4   0   0 918   1   0   1   1   2   1   3   3   1   0]
 [  1   1   2   1   3   2 937   1   1   2   0   1   0   0   0   1]
 [  0   1   3   1   2   2   0 930   0   2   0   1   1   0   1   0]
 [  0   2   3   3   2   6   1   2 871   2   3   8   4   0   0   1]
 [  1   0   8   1   0   0   1   0   0 890   0   0   3   1   0   2]
 [  1   1   0   1   2   2   0   1   0   3 900   1   2   3   2   0]
 [  2   4   3   1   3   1   0   1   1   0   0 944   1   1   1   1]
 [  4   0   0   0   0   2   3   3   1   0   2   2 934   2   0   3]
 [  0   1   0   0   2   2   1   0   1   0   4   1   0 969   0   2]
 [  0   0   1   0   2   0   0   0   2   2   1   1   2   0 968 

0.9800666666666666

In [35]:
#17
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[908   2   1   2   1   0   0   0   0   1   1   3   0   2   0   1]
 [  2 950   0   1   1   0   2   0   0   3   1   2   2   1   0   1]
 [  0   0 886   2   3   0   0   3   1   4   0   0   1   0   1   0]
 [  0   1   0 900   2   2   3   2   2   3   0   2   1   2   1   1]
 [  0   0   0   0 873   1   0   1   6   2   1   1   0   1   0   1]
 [  0   0   3   0   0 920   1   0   1   1   1   1   4   3   1   0]
 [  1   1   1   2   2   2 938   1   1   1   0   2   0   0   0   1]
 [  0   1   3   1   2   1   0 930   0   2   1   1   1   0   1   0]
 [  0   2   3   3   2   4   1   3 874   2   3   8   2   0   0   1]
 [  1   0   9   1   1   0   1   0   0 889   0   0   2   1   0   2]
 [  1   1   1   1   2   2   0   1   1   3 899   1   3   2   1   0]
 [  2   3   4   1   3   1   0   1   1   0   0 943   1   2   1   1]
 [  4   0   0   0   0   1   1   3   1   1   1   2 937   2   0   3]
 [  0   2   1   1   2   1   1   0   1   0   4   1   0 967   0   2]
 [  0   0   1   0   0   0   0   0   2   2   1   1   2   0 971 

0.9808

In [38]:
#20
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[908   1   1   2   2   0   0   0   0   1   1   2   0   2   0   2]
 [  2 950   0   1   1   0   2   0   0   3   1   2   2   1   0   1]
 [  0   0 887   2   3   0   0   2   1   4   0   0   1   0   1   0]
 [  0   0   0 903   1   2   1   2   2   4   0   2   1   2   1   1]
 [  0   0   1   0 874   1   0   1   3   2   1   2   0   1   0   1]
 [  0   1   3   0   0 919   1   0   1   1   1   1   4   3   1   0]
 [  1   1   1   1   2   2 939   1   1   1   0   2   0   0   0   1]
 [  0   1   3   1   2   1   0 931   0   2   1   0   1   0   1   0]
 [  0   2   3   3   2   4   1   3 873   2   3   8   3   0   0   1]
 [  1   0   8   1   1   0   1   0   0 891   0   0   1   1   0   2]
 [  0   1   1   1   1   2   0   1   1   3 900   1   3   3   1   0]
 [  2   4   3   1   3   1   0   1   1   0   0 943   1   2   1   1]
 [  3   0   0   0   0   1   2   3   2   1   1   2 936   2   0   3]
 [  0   1   0   1   2   1   1   0   1   0   4   2   1 967   0   2]
 [  0   0   1   0   0   0   0   0   2   2   1   1   2   0 971 

0.9812

In [41]:
#25
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[908   2   2   2   1   0   0   0   0   1   1   2   0   2   0   1]
 [  2 950   0   1   1   0   2   0   0   3   1   2   2   1   0   1]
 [  0   0 885   2   3   0   1   3   1   4   0   0   1   0   1   0]
 [  0   0   0 902   1   2   3   2   2   3   0   2   1   2   1   1]
 [  0   1   0   0 872   1   0   2   5   2   1   1   0   1   0   1]
 [  0   1   3   0   0 917   1   0   1   1   2   1   4   3   1   1]
 [  1   1   0   1   2   2 939   1   1   2   0   2   0   0   0   1]
 [  0   1   3   1   2   1   0 931   0   2   1   0   1   0   1   0]
 [  0   2   3   3   2   4   2   2 873   2   3   8   2   1   0   1]
 [  2   0  10   1   1   0   1   0   0 887   0   0   2   1   0   2]
 [  0   1   1   1   3   1   0   1   0   3 899   1   3   3   2   0]
 [  2   4   4   1   3   1   0   1   1   0   0 943   1   1   1   1]
 [  3   0   0   0   0   1   2   3   2   0   2   1 938   1   0   3]
 [  0   1   1   1   2   1   1   0   1   0   4   1   0 968   0   2]
 [  0   0   1   0   1   0   0   0   1   2   1   1   2   0 970 

0.9805333333333334

In [44]:
#40
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[907   2   1   2   1   0   0   0   1   1   1   2   1   2   0   1]
 [  3 949   0   1   1   0   2   0   0   3   1   2   2   1   0   1]
 [  0   0 886   2   3   0   1   2   1   4   0   0   1   0   1   0]
 [  0   0   0 903   1   2   2   2   2   3   0   2   1   2   1   1]
 [  1   0   0   0 872   1   1   1   5   3   1   1   0   0   0   1]
 [  0   1   3   0   0 915   1   0   1   1   4   1   5   3   1   0]
 [  1   1   0   1   2   2 938   1   1   3   0   2   0   0   0   1]
 [  0   2   3   1   2   2   0 929   0   2   1   0   1   0   1   0]
 [  0   1   3   3   2   5   1   2 877   2   2   7   2   0   0   1]
 [  1   0   9   1   1   0   1   0   0 891   0   0   0   1   0   2]
 [  0   1   1   1   2   2   0   1   1   3 901   1   2   2   1   0]
 [  2   3   3   1   4   1   0   1   2   0   0 942   1   1   1   2]
 [  3   0   0   0   0   2   1   3   2   0   1   1 937   2   0   4]
 [  0   1   0   0   2   1   1   0   1   0   5   1   1 968   0   2]
 [  0   0   0   0   1   0   0   0   2   2   1   1   2   0 970 

0.9806666666666667

In [47]:
#64
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[904   2   2   3   1   0   0   0   1   1   1   2   1   2   0   2]
 [  3 947   0   1   1   0   2   0   0   3   1   4   2   1   0   1]
 [  0   0 886   2   3   0   0   3   1   4   0   0   1   0   1   0]
 [  0   0   0 903   1   2   2   2   2   3   0   2   1   2   1   1]
 [  1   0   0   0 869   1   1   3   5   3   1   2   0   0   0   1]
 [  0   1   3   0   0 917   1   0   1   1   3   1   4   3   1   0]
 [  1   1   1   1   3   2 939   1   1   2   0   1   0   0   0   0]
 [  0   2   3   1   2   2   0 929   0   2   1   0   1   0   1   0]
 [  0   2   3   3   2   4   2   2 875   2   2   7   3   0   0   1]
 [  1   0   9   1   1   0   1   0   0 889   0   0   1   1   1   2]
 [  0   1   1   1   3   2   0   1   1   3 898   1   4   2   1   0]
 [  2   4   4   1   3   1   0   1   2   0   0 941   1   1   1   2]
 [  3   0   0   1   0   2   1   3   2   0   1   2 936   2   0   3]
 [  0   2   0   0   2   1   1   0   1   0   5   2   0 967   0   2]
 [  1   0   0   0   1   1   0   0   2   2   0   1   1   1 969 

0.9796

In [50]:
#50
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[907   2   1   2   1   0   0   0   1   1   1   2   1   2   0   1]
 [  3 948   0   1   1   0   2   0   0   3   1   3   2   1   0   1]
 [  0   0 885   2   3   0   1   3   1   4   0   0   1   0   1   0]
 [  0   0   0 902   1   2   3   2   2   3   0   2   1   2   1   1]
 [  1   0   0   0 871   1   1   1   6   3   1   1   0   0   0   1]
 [  0   0   3   0   0 918   1   0   1   1   3   1   4   3   1   0]
 [  1   1   1   1   3   2 939   1   1   2   0   1   0   0   0   0]
 [  0   2   3   1   2   2   0 929   0   2   1   0   1   0   1   0]
 [  0   2   3   3   2   5   2   2 873   2   2   8   3   0   0   1]
 [  1   0   9   1   1   0   1   0   0 890   0   0   0   2   0   2]
 [  0   1   1   1   2   2   0   1   1   3 900   1   3   2   1   0]
 [  2   4   3   1   3   1   0   1   2   0   0 942   1   1   1   2]
 [  3   0   0   1   0   2   1   3   2   0   1   2 936   2   0   3]
 [  0   2   0   0   2   1   1   0   1   0   6   2   0 966   0   2]
 [  1   0   0   0   1   0   0   0   2   2   1   1   1   1 969 

0.9801333333333333

In [53]:
#45
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[907   2   1   2   1   0   0   0   1   1   1   2   1   2   0   1]
 [  3 949   0   1   1   0   2   0   0   3   1   2   2   1   0   1]
 [  0   0 886   2   3   0   1   2   1   4   0   0   1   0   1   0]
 [  0   0   0 902   1   2   2   2   2   3   0   2   1   3   1   1]
 [  1   0   0   0 869   1   1   2   6   3   1   2   0   0   0   1]
 [  0   0   3   0   0 916   1   0   1   1   4   1   5   3   1   0]
 [  1   1   0   1   3   2 939   1   1   3   0   1   0   0   0   0]
 [  0   2   3   1   2   2   0 929   0   2   1   0   1   0   1   0]
 [  0   2   3   3   2   3   2   2 876   2   2   7   3   0   0   1]
 [  1   0   8   1   1   0   1   0   0 890   0   0   0   2   1   2]
 [  0   1   1   1   2   2   0   1   1   3 901   1   2   2   1   0]
 [  2   4   3   1   4   1   0   1   2   0   0 941   1   1   1   2]
 [  3   0   0   0   0   2   1   3   1   0   2   1 938   2   0   3]
 [  0   2   0   0   2   1   1   0   1   0   7   3   0 964   0   2]
 [  0   0   0   0   1   0   0   0   2   2   1   1   2   1 969 

0.9801333333333333

In [56]:
#42
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[906   2   1   2   1   0   0   0   1   1   1   2   0   3   0   2]
 [  3 949   0   1   1   0   2   0   0   3   1   2   2   1   0   1]
 [  0   0 886   2   3   0   1   2   1   4   0   0   1   0   1   0]
 [  0   0   0 903   1   2   2   2   2   3   0   2   1   2   1   1]
 [  1   0   0   0 871   1   1   1   6   3   1   1   0   0   0   1]
 [  0   0   3   0   0 915   1   0   1   1   4   1   5   3   1   1]
 [  1   1   0   1   3   2 939   1   1   3   0   1   0   0   0   0]
 [  0   2   3   1   2   2   0 929   0   2   1   0   1   0   1   0]
 [  0   2   3   3   2   3   2   2 877   2   2   7   2   0   0   1]
 [  1   0   9   1   1   0   1   0   0 891   0   0   0   1   0   2]
 [  0   1   1   1   2   2   0   1   1   3 901   1   2   2   1   0]
 [  2   3   3   1   4   1   0   1   2   0   0 942   1   1   1   2]
 [  3   0   0   0   0   2   1   3   2   0   1   2 937   2   0   3]
 [  0   2   0   0   2   1   1   0   1   0   6   2   1 965   0   2]
 [  0   0   0   0   1   0   0   0   1   2   1   1   2   0 971 

0.9805333333333334

In [59]:
#41
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[907   2   1   2   1   0   0   0   1   1   1   2   1   2   0   1]
 [  3 948   0   1   1   0   2   0   0   3   1   3   2   1   0   1]
 [  0   0 886   2   3   0   1   2   1   4   0   0   1   0   1   0]
 [  0   0   0 903   1   2   2   2   2   3   0   2   1   2   1   1]
 [  1   0   0   0 871   1   1   1   6   3   1   1   0   0   0   1]
 [  0   0   3   0   0 915   1   0   1   1   4   1   5   3   1   1]
 [  1   1   0   1   3   2 939   1   1   3   0   1   0   0   0   0]
 [  0   2   3   1   2   2   0 929   0   2   1   0   1   0   1   0]
 [  0   1   4   3   2   4   1   2 877   2   2   7   2   0   0   1]
 [  1   0   9   1   1   0   1   0   0 891   0   0   0   1   0   2]
 [  0   1   1   1   2   2   0   1   1   3 901   1   2   2   1   0]
 [  2   4   4   1   4   1   0   1   2   0   0 940   1   1   1   2]
 [  3   0   0   0   0   2   1   3   2   0   1   1 937   2   0   4]
 [  0   1   0   0   2   1   1   0   1   0   6   2   1 966   0   2]
 [  0   0   0   0   1   0   0   0   1   2   1   1   2   0 971 

0.9804666666666667

In [62]:
#final k = 40
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[907   2   1   2   1   0   0   0   1   1   1   2   1   2   0   1]
 [  3 949   0   1   1   0   2   0   0   3   1   2   2   1   0   1]
 [  0   0 886   2   3   0   1   2   1   4   0   0   1   0   1   0]
 [  0   0   0 903   1   2   2   2   2   3   0   2   1   2   1   1]
 [  1   0   0   0 872   1   1   1   5   3   1   1   0   0   0   1]
 [  0   1   3   0   0 915   1   0   1   1   4   1   5   3   1   0]
 [  1   1   0   1   2   2 938   1   1   3   0   2   0   0   0   1]
 [  0   2   3   1   2   2   0 929   0   2   1   0   1   0   1   0]
 [  0   1   3   3   2   5   1   2 877   2   2   7   2   0   0   1]
 [  1   0   9   1   1   0   1   0   0 891   0   0   0   1   0   2]
 [  0   1   1   1   2   2   0   1   1   3 901   1   2   2   1   0]
 [  2   3   3   1   4   1   0   1   2   0   0 942   1   1   1   2]
 [  3   0   0   0   0   2   1   3   2   0   1   1 937   2   0   4]
 [  0   1   0   0   2   1   1   0   1   0   5   1   1 968   0   2]
 [  0   0   0   0   1   0   0   0   2   2   1   1   2   0 970 

0.9806666666666667

In [64]:
import joblib
joblib.dump(classifier, "personality.pkl")

['personality.pkl']